spring:
  application:
    name: StomatologyApp
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: error

server:
  servlet:
    session:
      timeout: 15m

