spring:
  application:
    name: StomatologyApp
  # Настройки подключения к PostgreSQL с дефолтными значениями для локальной разработки
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/stomatologyapp}
    username: ${SPRING_DATASOURCE_USERNAME:savelii}
    password: ${SPRING_DATASOURCE_PASSWORD:12345}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0

logging:
  file:
    name: logs/stomatology.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7
  level:
    root: INFO
    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: error

server:
  servlet:
    session:
      timeout: 15m
