spring:
  application:
    name: StomatologyApp
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0

logging:
  level:
    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: error

server:
  servlet:
    session:
      timeout: 15m